<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>HR_Management_System</RootNamespace>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>  
	
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="C:\Users\patri\.nuget\packages\microsoft.testplatform.testhost\18.0.1\build\net8.0\x64\testhost.dll" />
    <Content Remove="C:\Users\patri\.nuget\packages\microsoft.testplatform.testhost\18.0.1\build\net8.0\x64\testhost.exe" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\patri\.nuget\packages\nunit3testadapter\6.1.0\build\net8.0\Microsoft.Extensions.DependencyModel.dll" />
    <None Remove="C:\Users\patri\.nuget\packages\nunit3testadapter\6.1.0\build\net8.0\nunit.engine.api.dll" />
    <None Remove="C:\Users\patri\.nuget\packages\nunit3testadapter\6.1.0\build\net8.0\nunit.engine.core.dll" />
    <None Remove="C:\Users\patri\.nuget\packages\nunit3testadapter\6.1.0\build\net8.0\nunit.engine.dll" />
    <None Remove="C:\Users\patri\.nuget\packages\nunit3testadapter\6.1.0\build\net8.0\NUnit3.TestAdapter.pdb" />
    <None Remove="C:\Users\patri\.nuget\packages\nunit3testadapter\6.1.0\build\net8.0\testcentric.engine.metadata.dll" />
    <None Remove="C:\Users\patri\.nuget\packages\xunit.runner.visualstudio\3.1.5\build\net8.0\xunit.abstractions.dll" />
    <None Remove="C:\Users\patri\.nuget\packages\xunit.runner.visualstudio\3.1.5\build\net8.0\xunit.runner.visualstudio.testadapter.dll" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="8.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    <PackageReference Include="NUnit" Version="4.5.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\patri\.nuget\packages\nunit3testadapter\6.1.0\build\net8.0\NUnit3.TestAdapter.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\patri\.nuget\packages\nunit3testadapter\6.1.0\build\net8.0\NUnit3.TestAdapter.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\patri\.nuget\packages\nunit3testadapter\6.1.0\build\net8.0\NUnit3.TestAdapter.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\patri\.nuget\packages\nunit3testadapter\6.1.0\build\net8.0\NUnit3.TestAdapter.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\patri\.nuget\packages\nunit3testadapter\6.1.0\build\net8.0\NUnit3.TestAdapter.dll" />
  </ItemGroup>

</Project>
